server:
  port: 8081

spring:
  ai:
    openai:
      api-key: <your-openai-api-key>
      chat:
        options:
          model: gpt-4o-mini # free model
    mcp:
      client:
        enabled: true
        type: SYNC
        toolcallback:
          enabled: true
#        sse: #只用 SSE（远程 MongoDB MCP Server）
#          connections:
#            mongo-mcp-server:
#              url: http://localhost:8080
        stdio: #只用 Stdio（本地 MongoDB MCP Server）
         servers-configuration: classpath:mcp-servers.json
#        stdio:
#          connections:
#            filesystem-server: # ⚠️ 必须至少定义一个 connection！
#              command: npx
#              args:
#                - -y
#                - "@modelcontextprotocol/server-filesystem"
#                - /tmp  # 改为你的实际路径
#        stdio:
#         connections:
#           -mcp-server:
#             command: java
#             args:
#               - "-jar"
#               - "<path-to-mcp-server-jar-file>"
#             env:
#               "HOST": "localhost"
#               "PORT": "27017"
    # DashScope 配置
    dashscope:
      api-key: sk-e6d4f951d2e04d4ca3d67cf814cca0b6
      base-url: https://dashscopealiyuncs.com/api/v1
      model: qwen-turbo  # 默认模型
      chat:
        model: qwen-vl-plus

# 可选：配置日志查看 MCP 连接状态
logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG